abastos/abastos/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^sell/', include('sell.urls')),
    url(r'^$', views.homepage),
    url(r'^homepage/', views.homepage, name="homepage"),
    url(r'^byproduct/(?P<slug>[\w-]+)/$', views.byproduct, name="byproduct"),
    url(r'^products/', include('products.urls')),
    url(r'^locations/', include('locations.urls')),
    url(r'^myMessages/', include('myMessages.urls'))
]

urlpatterns+=staticfiles_urlpatterns()

abastos/locations/urls.py
from django.conf.urls import url
from . import views

app_name='locations'

urlpatterns=[
url(r'^locations-list/$', views.locations_list_view,name="locations_list"),
url(r'^publish/$', views.publish, name="publish"),
url(r'^(?P<slug>[\w-]+)/$',views.location_details, name="location_details"),
url(r'^delete/(?P<slug>[\w-]+)/$', views.location_delete,name="location_delete"),
]

abastos/sell/urls.py
from django.conf.urls import url
from . import views

app_name='sell'

urlpatterns=[
url(r'^sell-list/$', views.sell_list_view,name="sell_list"),
url(r'^publish/$', views.publish,name="publish"),
url(r'^(?P<slug>[\w-]+)/$',views.sell_details, name="sell_details"),
url(r'^delete/(?P<slug>[\w-]+)/$', views.sell_delete,name="sell_delete"),
url(r'^sell-list/by-location/$', views.sell_list_by_location, name="sell_list_by_location"),
url(r'^sell-list/by-date/$', views.sell_list_by_date, name="sell_list_by_date"),
url(r'^sell-list/by-author/$', views.sell_list_by_author, name="sell_list_by_author"),
]

abastos/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>

<html>
    <head>
      <meta-charset="utf-8">
      <link href="https://fonts.googleapis.com/css?family=Montserrat:200display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
      <link rel="stylesheet" href={% static 'styles.css' %} />
      <script src='https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.js'></script>
      <link href='https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css' rel='stylesheet' />
      <title>Homepage</title>
    </head>
    <body>
        <div class="menu">
        <ul>
          <li><a href="/homepage" class="logo">AbastoSimple</a></li>
          {% if user.is_superuser %}
          <li><a href="/products/products-list">Products</a></li>
          {% endif %}
          <li><a href="/sell/sell-list">Sell</a></li>

          <li><a href="/locations/locations-list">Locations</a></li>





          {% if user.is_authenticated %}
          <li style="margin-top: 24px; margin-right:2%; float:right; overflow: hidden;">
            <div id="user" onmouseover="mouseover()" onmouseout="mouseout()" style="color:white;">
              <i class="fas fa-user"></i> <span id="hey" style="padding-right:20px;">{{user.username}}</span>
              <div style="height:20px;">

              </div>

            </div>
            <div id="dropdown-content" onmouseover="mouseover()" onmouseout="mouseout()" style="font-size: 12px;  color:black; width:160px;  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); position: absolute; float:right; display:none; background-color:white;  ">
              <a id="item"  style="color:darkgrey;  float: none; display: block;" href="/accounts/informations"><i style="color:darkgrey" class="fas fa-user-cog"></i> My account</a>
              <a id="item"  style="color:darkgrey; float: none; display: block;" href="/myMessages/messages-list/received"><b><i style="color:darkgrey" class="fas fa-inbox"></i> My messages </b></a>
              <form class="logout" action="/accounts/logout/" method="post">
                {% csrf_token %}
              <button class="logout" style="color:red; border:0; font-family:'Montserrat', sans-serif; font-size: 18px; margin-bottom: 15%; margin-top: 15%;" type="submit"><i style="color:red;" class="fas fa-sign-out-alt"></i> Logout</button>

            </form>
            </div>

            </li>



          {% else %}

          <li style="float:right;"><a href="/accounts/login">Login</a></li>
          <li style="float:right;"><a href="/accounts/signup">Sign up</a></li>
          {% endif %}
        </ul>

      </div>
      <div class="wrapper">
        {% block content %}
        {% endblock %}
      </div>
    </body>

    <script>
            function mouseover() {
                document.getElementById("user").style.color = "#0f1136";
                document.getElementById("dropdown-content").style.display = "block";
            }


            function mouseout() {
                document.getElementById("user").style.color = "white";
                document.getElementById("dropdown-content").style.display = "none";
            }

        </script>
    </html>

abastos/templates/homepage.html
{% extends 'base_layout.html'%}

{% block content %}
{% load static from staticfiles %}
      <div class="container" >
        <h1 style="font-size:5vw;">AbastoSimple</h1>

        <div class="text" >
          <div class="element">
            <h5><img style="padding-right:15px" height=15 src="https://img.icons8.com/wired/64/000000/cursor.png"/>On the map, see where to shop.</h5>
          </div>
          <div class="element">
            <h5> <img style="padding-right:15px" height=15 src="https://img.icons8.com/wired/64/000000/search.png"/>Click on a location for details.</h5>
          </div>
          <div class="element">
            <h5> <img style="padding-right:15px" height=15 src="https://img.icons8.com/wired/64/000000/speech-bubble.png"/>Publish ads to inform people what you're selling.</h5>
          </div>

          <div style="text-align:center">
          <form style="font-size: 15px;"   action="javascript:getslug(this)"  method="post" enctype="multipart/form-data">
            <input type="hidden" name="length" value=8>
            {% csrf_token %}
            <label>Look for places selling:</label>
            <select id="cars" style="font-family: 'Montserrat', sans-serif;" name="product">
              {% for product in products %}
                <option value="{{product.name}}"> {{product.name}}</option>
              {% endfor %}
            </select>

            <input type="submit" style="font-size: 15px; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color: lightgreen; color:white; margin-top:3%;" value="Go" />
          </form>
          {% if size == 0 %}

            <h5 style="color:red;"> Sorry we don't have this product available on our platform</h5>

          {% endif %}
          <button type="button"  onclick="reset()" style="font-size: 15px; font-family: 'Montserrat', sans-serif; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color: orange; color:white; margin-top:1%;">Reset</button>
          </div><br>



          <div id='map' style="width:100%; height: 300px;"></div>
        </div>

      </div>

      <script>
      mapboxgl.accessToken = '{{token}}';
      var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [2.34, 48.85],
      zoom: 4,
      });


      var sell_list= [
         {% for sellpair in sellpairs %}
             {% if not forloop.first %},{% endif %}
             {
                 product: "{{ sellpair.product }}",
                 quantity: "{{ sellpair.quantity }}",
                 slug:"{{ sellpair.slug }}",
                 location: "{{sellpair.sell.location}}"
             }
         {% endfor %}
       ];


      if ( '{{type}}' == "none"){

      var locations_list = [
         {% for loc in locations %}
             {% if not forloop.first %},{% endif %}
             {
                 name: "{{ loc.name }}",
                 slug: "{{ loc.slug }}",
                 north: "{{ loc.north_coordinate }}",
                 east: "{{loc.east_coordinate}}"
             }
         {% endfor %}
       ];



    var index=0;
    while(index<locations_list.length){
      var content="";
      loc=locations_list[index];

      for (let i = 0; i < sell_list.length; i++) {
            var sell=sell_list[i];
            if (sell.location === loc.name){
              content+="<a class='product' href='/sell/"+sell.slug+"'>"+sell.product+"("+sell.quantity+") </a><br>";
            }
        }
      var link="/locations/"+loc.slug;
      var acontent="<a class='visit' href='"+link+"'> Visit store </a>";
      console.log(acontent)


      content+=acontent;
      console.log(content);


      new mapboxgl.Marker()
      .setLngLat([loc.east, loc.north])
      .addTo(map)
      .setPopup(new mapboxgl.Popup().setHTML(content));

      index++;
      }

    }
    else {
        console.log(sell_list);


        var locations_list = [
           {% for loc in locations %}
               {% if not forloop.first %},{% endif %}
               {
                   name: "{{ loc.name }}",
                   slug: "{{ loc.slug }}",
                   north: "{{ loc.north_coordinate }}",
                   east: "{{loc.east_coordinate}}",
                   displayed: false,
                   count: 0
               }
           {% endfor %}
         ];
         //console.log(locations_list);
               for (let i = 0; i < sell_list.length; i++) {
                     var sell=sell_list[i];
                      for (let j = 0; j < locations_list.length; j++) {
                          if(locations_list[j].name==sell.location){

                              locations_list[j].count+=parseInt(sell.quantity);
                              locations_list[j].displayed=true;
                          }
                     }
                 }

        for (let j = 0; j < locations_list.length; j++) {
            loc=locations_list[j]
            var link="/locations/"+loc.slug;
            if(loc.displayed){
              new mapboxgl.Marker()
              .setLngLat([loc.east, loc.north])
              .addTo(map)
              .setPopup(new mapboxgl.Popup().setHTML("<h2>"+locations_list[j].count+" "+sell_list[0].product+" available</h2><br><a class='visit' href='"+link+"'>Visit here</a>"));

            }


        }









    }



 //console.log(locations_list[0]);


    function getslug(){
      slug=document.getElementById("cars").value;
      window.location.href="/byproduct/"+slug;

    }

    function reset(){
        window.location.href="/homepage";
        slug=document.getElementById("cars").value;
        ref="/homepage/byproduct/"+slug;
        console.log(ref);

    }




      </script>
{% endblock %}

abastos/templates/selllist.html
{% extends 'base_layout.html'%}

{% block content %}
{% load static from staticfiles %}
      <h1>Products' sell</h1>
      <button style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color:#ff5f3b; border:0; font-family:'Montserrat', sans-serif; font-size: 25px;"><a  style="color:white; text-decoration:inherit;" href="/sell/publish" >
      Publish here </a></button>
      <h2> People are selling: </h2>

      <h3>Order by :</h3>

      {% if type == "product" %}
      <select onchange="product();" id="choice" style="margin-bottom: 3%;box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);font-family:'Montserrat', sans-serif;font-size: 25px;">
        <option id="product" value="1">
          Product
        </option>
        <option id="author" value="2">
          Author
        </option>
        <option id="location" value="3">
          Location
        </option>
        <option id="date" value="4">
          Date
        </option>
      </select>

      <div class="sellpairs" >
        {% for sellpair in sellpairs %}
          <div class="sellpair">
              <div class="container" style="margin-top:30px;">
                <h2 style="padding-top:2%;">
                    <img style="height:30px;" src="{{sellpair.product.url}}"/>
                  {{sellpair.product}}
                </h2>
                <h3 style="color: #ff5f3b;">
                  Quantity : {{sellpair.quantity}}
                </h3>
                <div  id='{{sellpair.id}}' style="background-color: #f0f0f0; display:none; margin-left:20%; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px;">
                  <b>Published:</b> {{sellpair.sell.date}} <br />
                  <b>Seller:</b> {{sellpair.sell.author}} <br />
                  <b>Location:</b> <a style="text-decoration:none; color:darkgrey;" href="{% url 'locations:location_details' slug=sellpair.sell.location.slug %}">{{sellpair.sell.location}}</a>
                </div>
                <button id="details" onclick="myFunction({{sellpair.id}})" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: green; color:white;margin-top: 3%; margin-bottom: 2%;"> View details</button>
                {% if user == sellpair.sell.author %}
                <button id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: orange; color:white;margin-top: 3%; margin-bottom: 2%;">
                <a style="text-decoration:none; color:white;" href="{% url 'sell:sell_details' slug=sellpair.slug  %}">Modify</a></button>
                <button id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: red; color:white;margin-top: 3%; margin-bottom: 2%;"> <a style="text-decoration:none; color:white;" href="{% url 'sell:sell_delete' slug=sellpair.slug %}">Delete</a></button>
                {% endif %}
              </div>
          </div>
        {% endfor %}
      </div>

      {% elif type == "author" %}
      <select onchange="author();" id="choice" style="margin-bottom: 3%;box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);font-family:'Montserrat', sans-serif;font-size: 25px;">
        <option id="author" value="1">
          Author
        </option>
        <option id="product" value="2">
          Product
        </option>
        <option id="location" value="3">
          Location
        </option>
        <option id="date" value="4">
          Date
        </option>
      </select>

      <div class="sellpairs" >
        {% for sellpair in sellpairs %}
          <div class="sellpair">
              <div class="container" style="margin-top:30px;">
                <h2 style="padding-top:2%;">
                  <i class="far fa-user"></i>
                  {{sellpair.sell.author}}
                </h2>
                <h4 style="color: #ff5f3b;">
                  <b>{{sellpair.sell.date}}<b>
                </h4>
                <div  id='{{sellpair.id}}' style="background-color: #f0f0f0; display:none; margin-left:20%; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px;">
                  <b>Product:</b> {{sellpair.product}} <br />
                  <b>Quantity:</b> {{sellpair.quantity}} <br />
                  <b>Location:</b> <a style="text-decoration:none; color:darkgrey;" href="{% url 'locations:location_details' slug=sellpair.sell.location.slug %}">{{sellpair.sell.location}}</a>
                </div>
                <button id="details" onclick="myFunction({{sellpair.id}})" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: green; color:white;margin-top: 3%; margin-bottom: 2%;"> View details</button>
                {% if user != sellpair.sell.author %}
                <button id="details" onclick="myFunc();" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: lightblue; color:white;margin-top: 3%; margin-bottom: 2%;"> Send message</button>
                {% endif %}
                {% if user == sellpair.sell.author %}
                <button id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: orange; color:white;margin-top: 3%; margin-bottom: 2%;">
                <a style="text-decoration:none; color:white;" href="{% url 'sell:sell_details' slug=sellpair.slug  %}">Modify</a></button>
                <button id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: red; color:white;margin-top: 3%; margin-bottom: 2%;"> <a style="text-decoration:none; color:white;" href="{% url 'sell:sell_delete' slug=sellpair.slug %}">Delete</a></button>
                {% endif %}
              </div>
          </div>
        {% endfor %}
      </div>

      {% elif type == "location" %}
      <select onchange="location2();" id="choice" style="margin-bottom: 3%;box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);font-family:'Montserrat', sans-serif;font-size: 25px;">
        <option id="location" value="1">
          Location
        </option>
        <option id="product" value="2">
          Product
        </option>
        <option id="author" value="3">
          Author
        </option>
        <option id="date" value="4">
          Date
        </option>
      </select>

      <div class="sellpairs" >
        {% for sellpair in sellpairs %}
          <div class="sellpair">
              <div class="container" style="margin-top:30px;">
                <h2 style="padding-top:2%;">
                  <img style="height:30px;" src="https://img.icons8.com/wired/64/000000/building.png"/>
                  {{sellpair.sell.location}}
                </h2>
                <h4 style="color: #ff5f3b;">
                   {{sellpair.sell.date}}
                </h4>
                <div  id='{{sellpair.id}}' style="background-color: #f0f0f0; display:none; margin-left:20%; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px;">
                  <b>Product:</b> {{sellpair.product}} <br />
                  <b>Quantity:</b> {{sellpair.quantity}} <br />
                  <b>Author:</b> {{sellpair.sell.author}} <br />

                </div>
                <button id="details" onclick="myFunction({{sellpair.id}})" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: green; color:white;margin-top: 3%; margin-bottom: 2%;"> View details</button>
                {% if user == sellpair.sell.author %}
                <button id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: orange; color:white;margin-top: 3%; margin-bottom: 2%;">
                <a style="text-decoration:none; color:white;" href="{% url 'sell:sell_details' slug=sellpair.slug  %}">Modify</a></button>
                <button id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: red; color:white;margin-top: 3%; margin-bottom: 2%;"> <a style="text-decoration:none; color:white;" href="{% url 'sell:sell_delete' slug=sellpair.slug %}">Delete</a></button>
                {% endif %}
              </div>
          </div>
        {% endfor %}
      </div>

      {% elif type == "date" %}
      <select onchange="date2();" id="choice" style="margin-bottom: 3%;box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);font-family:'Montserrat', sans-serif;font-size: 25px;">
        <option id="date" value="1">
          Date
        </option>
        <option id="product" value="2">
          Product
        </option>
        <option id="author" value="3">
          Author
        </option>
        <option id="location" value="4">
          Location
        </option>
      </select>

      <div class="sellpairs" >
        {% for sellpair in sellpairs %}
          <div class="sellpair">
              <div class="container" style="margin-top:30px;">
                <h2 style="padding-top:2%;">

                  {{sellpair.sell.date}}
                </h2>
                <h4 style="color: #ff5f3b;">
                  {{sellpair.sell.author}}
                </h4>
                <div  id='{{sellpair.id}}' style="background-color: #f0f0f0; display:none; margin-left:20%; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px;">
                  <b>Product:</b> {{sellpair.product}} <br />
                  <b>Quantity:</b> {{sellpair.quantity}} <br />
                  <b>Location:</b> <a style="text-decoration:none; color:darkgrey;" href="{% url 'locations:location_details' slug=sellpair.sell.location.slug %}">{{sellpair.sell.location}}</a>
                </div>
                <button id="details" onclick="myFunction({{sellpair.id}})" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: green; color:white;margin-top: 3%; margin-bottom: 2%;"> View details</button>
                {% if user == sellpair.sell.author %}
                <button id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: orange; color:white;margin-top: 3%; margin-bottom: 2%;">
                <a style="text-decoration:none; color:white;" href="{% url 'sell:sell_details' slug=sellpair.slug  %}">Modify</a></button>
                <button id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: red; color:white;margin-top: 3%; margin-bottom: 2%;"> <a style="text-decoration:none; color:white;" href="{% url 'sell:sell_delete' slug=sellpair.slug %}">Delete</a></button>
                {% endif %}
              </div>
          </div>
        {% endfor %}
      </div>
      {% endif %}






<script>
function myFunction(value) {
  var x = document.getElementById(value);
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}

function mySlug(val1, val2){
  var mySlug= toString(val1)+"-"+toString(val2);
  return mySlug;
}

function product(){
  text=document.getElementById("choice").value;
  if (text==1){
    window.location.href="/sell/sell-list/";
  }
  else if(text==2){
    window.location.href="/sell/sell-list/by-author/";
  }
  else if(text==3){
    window.location.href="/sell/sell-list/by-location/";
  }
  else{
    window.location.href="/sell/sell-list/by-date/";
  }
}

function author(){
  text=document.getElementById("choice").value;
  if (text==1){
    window.location.href="/sell/sell-list/by-author/";
  }
  else if(text==2){
    window.location.href="/sell/sell-list/";
  }
  else if(text==3){
    window.location.href="/sell/sell-list/by-location/";
  }
  else{
    window.location.href="/sell/sell-list/by-date/";
  }
}

function location2(){
  text=document.getElementById("choice").value;
  if (text==1){
    window.location.href="/sell/sell-list/by-location/";
  }
  else if(text==2){
    window.location.href="/sell/sell-list/";
  }
  else if(text==3){
    window.location.href="/sell/sell-list/by-author/";
  }
  else{
    window.location.href="/sell/sell-list/by-date/";
  }
}

function date2(){
  text=document.getElementById("choice").value;
  if (text==1){
    window.location.href="/sell/sell-list/by-date/";
  }
  else if(text==2){
    window.location.href="/sell/sell-list/";
  }
  else if(text==3){
    window.location.href="/sell/sell-list/by-author/";
  }
  else{
    window.location.href="/sell/sell-list/by-location/";
  }
}
function myFunc(){
  window.location.href="/myMessages/new-message/"
}


</script>
{% endblock %}