abastos/abastos/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^sell/', include('sell.urls')),
    url(r'^$', views.homepage),
    url(r'^homepage/', views.homepage, name="homepage"),
    url(r'^byproduct/(?P<slug>[\w-]+)/$', views.byproduct, name="byproduct"),
    url(r'^products/', include('products.urls')),
    url(r'^locations/', include('locations.urls')),
    url(r'^myMessages/', include('myMessages.urls'))
]

urlpatterns+=staticfiles_urlpatterns()

abastos/products/urls.py
from django.conf.urls import url
from . import views

app_name='products'

urlpatterns=[
url(r'^products-list/$', views.products_list_view,name="products_list"),
url(r'^publish/$', views.publish,name="products_list"),
url(r'^(?P<slug>[\w-]+)/$',views.product_details, name="product_details"),
url(r'^delete/(?P<slug>[\w-]+)/$', views.product_delete,name="product_delete"),
]

abastos/sell/urls.py
from django.conf.urls import url
from . import views

app_name='sell'

urlpatterns=[
url(r'^sell-list/$', views.sell_list_view,name="sell_list"),
url(r'^publish/$', views.publish,name="publish"),
url(r'^(?P<slug>[\w-]+)/$',views.sell_details, name="sell_details"),
url(r'^delete/(?P<slug>[\w-]+)/$', views.sell_delete,name="sell_delete"),
url(r'^sell-list/by-location/$', views.sell_list_by_location, name="sell_list_by_location"),
url(r'^sell-list/by-date/$', views.sell_list_by_date, name="sell_list_by_date"),
url(r'^sell-list/by-author/$', views.sell_list_by_author, name="sell_list_by_author"),
]

abastos/products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name=models.CharField(max_length=20)
    url=models.CharField(max_length=1000,default="foobar")
    

    def __str__(self):
        return self.name

abastos/products/forms.py
from django import forms
from .import models

class CreateProduct(forms.ModelForm):
    class Meta:
        model=models.Product
        fields=['name','url']

abastos/products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Product
from sell.models import SellPair
from .import forms
from django.http import HttpResponse
import re
from urlparse import urlparse

def products_list_view(request):
    products=Product.objects.all().order_by('name')
    sellpairs=SellPair.objects.all().order_by('product')
    return render(request, "products/productslist.html",{'products':products, 'sellpairs':sellpairs} )

@login_required(login_url="/accounts/login/")
def publish(request):
    isName=True
    isUrl=True
    notAlreadyExists=True
    sellpairs_list=SellPair.objects.all().order_by('product')
    if request.method=="POST":
        products=Product.objects.all().order_by('name')
        name=request.POST.get('name')
        url=request.POST.get('url')
        already=Product.objects.filter(name=name).count()
        if(already!=0):
            notAlreadyExists=False
        if(correct_name(name)==False):
            isName=False
        if(correct_url(url)==False):
            isUrl=False
        if(correct_name(name)==True and correct_url(url)==True and notAlreadyExists==True):
            product=Product.objects.create(name=name, url=url)
            product.save()
            return render(request, 'products/productslist.html', {'products':products,'user':request.user, 'sellpairs':sellpairs_list})
        else:
            return render(request, 'products/publish.html', {'user':request.user,'isName': isName, 'isUrl':isUrl, 'notAlreadyExists':notAlreadyExists})

    return render(request, 'products/publish.html', {'user':request.user,'isName': isName, 'isUrl':isUrl,'notAlreadyExists':notAlreadyExists})


def correct_name(s):
    regex = re.compile('[@_!#$%^&*()<>?/\|}{~:1234567890]')
    if(regex.search(s) == None):
        return True
    return False

def correct_url(url):
    result=urlparse(url)
    if(result.scheme!= "" and result.netloc!=""):
        return True
    return False

def product_details(request,slug):
    isName=True
    isUrl=True
    notAlreadyExists=True
    products=Product.objects.all().order_by('name')
    sellpairs_list=SellPair.objects.all().order_by('product')
    user=request.user
    if request.method=='POST':
        product= Product.objects.get(name=slug)
        new_name=request.POST.get('name')
        new_url=request.POST.get('url')
        if (correct_name(new_name)==False):
            isName=False
        if(correct_url(new_url)==False):
            isUrl=False
        already=Product.objects.filter(name=new_name).count()
        if(already!=0):
            if(new_name!=product.name):
                notAlreadyExists=False
        if(isName==True and isUrl==True and notAlreadyExists==True):
            product.name=new_name
            product.url=new_url
            product.save()
            return render(request, 'products/productslist.html', {'products':products,'user':request.user, 'sellpairs':sellpairs_list})
        else:
            return render(request, 'products/product_details.html', {'product':product,'user':request.user,'isName': isName, 'isUrl':isUrl,'notAlreadyExists':notAlreadyExists})
    product= Product.objects.get(name=slug)
    return render (request, 'products/product_details.html', {'product':product, 'user':user,'isName': isName, 'isUrl':isUrl, 'notAlreadyExists':notAlreadyExists})

def product_delete(request,slug):
    product= Product.objects.get(name=slug)
    sellpairs=SellPair.objects.filter(product=product)
    sellpairs_list=SellPair.objects.all().order_by('product')
    print(product)
    for s in sellpairs:
        s.delete()
    product.delete()
    products=Product.objects.all().order_by('name')
    user=request.user
    return render(request, 'products/productslist.html', {'products':products,'user':request.user, 'sellpairs':sellpairs_list})

abastos/templates/products/product_details.html
{% extends 'base_layout.html'%}

{% block content %}
{% load static from staticfiles %}
      <button id="details" style="float:left; margin-left: 10%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 20px;background-color: green; color:white;">
      <a style="text-decoration:none; color:white;" href="/products/products-list"><i class="fas fa-arrow-circle-left"></i> Back to products' list</a></button><br />

      <h1>Details of the product</h1>

      <div id="actual_product" style="  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color: white; margin-left:20%; font-size: 23px; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px; margin-bottom: 3%;" >
          <img style="height:30px;" src="{{product.url}}"/> {{product.name}}
      </div>
      <h2 style="margin-bottom:2%;"> Do you want to make changes ? </h2>
      {% if isName == False %}
      <h5 style="color:red;">The name format isn't correct</h5>
      {% endif %}
      {% if isUrl == False %}
      <h5 style="color:red;">The url format isn't correct</h5>
      {% endif %}
      {% if notAlreadyExists == False %}
      <h5 style="color:red;">This product already exists</h5>
      {% endif %}
      <form action="{% url 'products:product_details' slug=product.name %}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="length" value=8>
        {% csrf_token %}
        <label><b>Name</b></label>
        <input type="text" name="name"  value="{{product.name}}">
        <label><b>URL</b></label>
        <input type="text" name="url"  value="{{product.url}}"><br />
        <input type="submit" style="font-size: 25px;  margin-top: 3%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color:orange; color:white;" value="Modify" />
        </form>








      </div>
{% endblock %}

abastos/templates/products/productslist.html
{% extends 'base_layout.html'%}

{% block content %}
{% load static from staticfiles %}
      <h1>Products sold on the platform</h1>
      <button style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); margin-bottom:5%; background-color:#ff5f3b; border:0; font-family:'Montserrat', sans-serif; font-size: 25px;"><a  style="color:white; text-decoration:inherit;" href="/products/publish" >
      Create new product </a></button>



      <div class="products">
        {% for product in products %}
          <div class="sellpair">
              <div class="container" style="margin-top:30px;">

                <h2 style="padding-top:2%;">
                    <img style="height:30px;" src="{{product.url}}"/>
                  {{product.name}}
                </h2>
                <div  id='{{product.id}}' style="background-color: #f0f0f0; display:none; margin-left:20%; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px;">
                  <ul style="list-style-type:none;">
                    {% for sellpair in sellpairs %}
                    {% if sellpair.product == product %}

                      <li style="background-color:white; margin-right:5%; padding-top:2%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); margin-bottom:2%;">
                        <b>{{sellpair.quantity}}</b> units of {{sellpair.product}}<br />
                        <em><b>{{sellpair.sell.author}}</b> in <b>{{sellpair.sell.location}}</b></em> <br />
                        <a id="ad" style=" color: #616161; " href="{% url 'sell:sell_details' slug=sellpair.slug  %}"> See details </a>
                      </li>

                    {% endif %}
                    {% endfor %}
                  </ul>
                </div>
                <button id="details" onclick="myFunction({{product.id}})" style=" box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: green; color:white;margin-top: 3%; margin-bottom: 2%;"> View ads</button>
                {% if user.is_superuser %}
                <button id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: orange; color:white;margin-top: 3%; margin-bottom: 2%;"> <a style="text-decoration:none; color:white;" href="{% url 'products:product_details' slug=product.name %}">Modify</a></button>
                <button id="details"  style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: red; color:white;margin-top: 3%; margin-bottom: 2%;"> <a style="text-decoration:none; color:white;" href="{% url 'products:product_delete'  slug=product.name%}">Delete</a></button>


                {% endif %}




              </div>
          </div>

        {% endfor %}

      </div>








      <script>
      function myFunction(value) {
        var x = document.getElementById(value);
        if (x.style.display === "none") {
          x.style.display = "block";
          
        } else {
          x.style.display = "none";
        }
      }


      </script>
{% endblock %}

abastos/templates/products/publish.html
{% extends 'base_layout.html'%}

{% block content %}
{% load static from staticfiles %}
    <button id="details" style="float:left; margin-left: 10%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 20px;background-color: green; color:white;">
    <a style="text-decoration:none; color:white;" href="/products/products-list"><i class="fas fa-arrow-circle-left"></i> Back to products' list</a></button><br />

      <h1>Add a new product here</h1>

      <h2 style="margin-bottom: 3%;"> What product do you want to add ? </h2>

      {% if isName == False %}
      <h5 style="color:red;">The name format isn't correct</h5>
      {% endif %}
      {% if isUrl == False %}
      <h5 style="color:red;">The url format isn't correct</h5>
      {% endif %}
      {% if notAlreadyExists == False %}
      <h5 style="color:red;">This product already exists</h5>
      {% endif %}


      <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="length" value=8>
        {% csrf_token %}

        <label ><b>Name:</b></label>
        <input name="name" style="margin-top:1%;margin-bottom:1%;" type="text"  />
        <label><b>Url:</b> </label>
        <input name="url" style="margin-top:1%;margin-bottom:1%;" type="text"  /><br>
        <input style="font-size: 25px; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color:lightblue; color:white;" type="submit" value="Add a new product" />
      </form>





      </div>
{% endblock %}