abastos/abastos/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^sell/', include('sell.urls')),
    url(r'^$', views.homepage),
    url(r'^homepage/', views.homepage, name="homepage"),
    url(r'^byproduct/(?P<slug>[\w-]+)/$', views.byproduct, name="byproduct"),
    url(r'^products/', include('products.urls')),
    url(r'^locations/', include('locations.urls')),
    url(r'^myMessages/', include('myMessages.urls'))
]

urlpatterns+=staticfiles_urlpatterns()

abastos/locations/urls.py
from django.conf.urls import url
from . import views

app_name='locations'

urlpatterns=[
url(r'^locations-list/$', views.locations_list_view,name="locations_list"),
url(r'^publish/$', views.publish, name="publish"),
url(r'^(?P<slug>[\w-]+)/$',views.location_details, name="location_details"),
url(r'^delete/(?P<slug>[\w-]+)/$', views.location_delete,name="location_delete"),
]

abastos/sell/urls.py
from django.conf.urls import url
from . import views

app_name='sell'

urlpatterns=[
url(r'^sell-list/$', views.sell_list_view,name="sell_list"),
url(r'^publish/$', views.publish,name="publish"),
url(r'^(?P<slug>[\w-]+)/$',views.sell_details, name="sell_details"),
url(r'^delete/(?P<slug>[\w-]+)/$', views.sell_delete,name="sell_delete"),
url(r'^sell-list/by-location/$', views.sell_list_by_location, name="sell_list_by_location"),
url(r'^sell-list/by-date/$', views.sell_list_by_date, name="sell_list_by_date"),
url(r'^sell-list/by-author/$', views.sell_list_by_author, name="sell_list_by_author"),
]

abastos/locations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Location(models.Model):
    id = models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    north_coordinate=models.FloatField()
    east_coordinate=models.FloatField()
    owner=models.ForeignKey(User)
    slug=models.CharField(max_length=50, default="none")

    def __str__(self):
        return self.name

abastos/locations/forms.py
from django import forms
from .import models

class CreateLocation(forms.ModelForm):
    class Meta:
        model=models.Location
        fields=['name','north_coordinate','east_coordinate']

abastos/locations/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Location
from sell.models import SellPair
from . import forms
from django.http import HttpResponse
import re


def locations_list_view(request):
    sellpairs=SellPair.objects.all().order_by('product')
    locations=Location.objects.all().order_by('owner')
    return render(request, "locations/locationslist.html", {'locations':locations, 'sellpairs':sellpairs} )

@login_required(login_url="/accounts/login/")
def publish(request):
    isName=True
    isLat=True
    isLong=True
    sellpairs_list=SellPair.objects.all().order_by('product')
    if request.method=="POST":
        locations=Location.objects.all().order_by('owner')
        form=forms.CreateLocation(request.POST, request.FILES)
        if form.is_valid():
            name=request.POST['name']
            slug=name.replace(" ", "-")
            slug=slug+"-"+str(request.user.username)
            north=request.POST['north_coordinate']
            east=request.POST['east_coordinate']
            owner=request.user
            if(correct_name(name)==False):
                isName=False
            if(correct_lat(north)==False):
                isLat=False
            if(correct_long(east)==False):
                isLong=False
            if(isLat==True and isLong==True and isName==True):
                location=Location.objects.create(name=name, north_coordinate=north, east_coordinate=east, owner=request.user, slug=slug)
                location.save()
                return render(request, 'locations/locationslist.html', {'user':request.user, 'locations':locations, 'sellpairs':sellpairs_list})
            else:
                return render(request, 'locations/publish.html', {'form':form,'user':request.user, 'isName':isName, 'isLong':isLong, "isLat":isLat })
    else:
        form=forms.CreateLocation()
    return render(request, 'locations/publish.html', {'form':form,'user':request.user, 'isName':isName,'isLong':isLong, "isLat":isLat })

def location_details(request, slug):
    locations=Location.objects.all().order_by('owner')
    user=request.user
    sellpairs_list=SellPair.objects.all().order_by('product')
    location= Location.objects.get(slug=slug)
    isName=True
    isLat=True
    isLong=True
    print(slug)
    if request.method=='POST':
        new_name=request.POST.get("name")
        new_nc=request.POST.get("north_coordinate")
        new_ec=request.POST.get("east_coordinate")
        slug=new_name.replace(" ", "-")
        slug=slug+"-"+(str(request.user.username))
        if(correct_name(new_name)==False):
            isName=False
        if(correct_lat(new_nc)==False):
            isLat=False
        if(correct_long(new_ec)==False):
            isLong=False
        if(isLat==True and isLong==True and isName==True):
            location.name=new_name
            location.north_coordinate=new_nc
            location.east_coordinate=new_ec
            location.slug=slug
            location.save()
            return render(request, 'locations/locationslist.html', {'user':user, 'locations':locations, 'sellpairs':sellpairs_list})
        else:
            return render(request, "locations/location_details.html", {'user':user, 'location':location,'isName':isName,'isLong':isLong, "isLat":isLat})
    return render(request, "locations/location_details.html", {'user':user, 'location':location,'isName':isName,'isLong':isLong, "isLat":isLat})

def correct_name(s):
    regex = re.compile('[@_!#$%^&*()<>?/\|}{~:1234567890]')
    if(regex.search(s) == None):
        return True
    return False

def correct_lat(lat):
    result = re.match("^(\+|-)?(?:90(?:(?:\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,6})?))$",lat)
    if (result==None):
        return False
    return True

def correct_long(long):
    result = re.match("^(\+|-)?(?:180(?:(?:\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\.[0-9]{1,6})?))$",long)
    if (result==None):
        return False
    return True

def location_delete(request,slug):
    location= Location.objects.get(slug=slug)
    sellpairs=SellPair.objects.all()

    print(location)
    for s in sellpairs:
        if s.sell.location==location:
            s.delete()
    location.delete()
    locations=Location.objects.all().order_by('owner')
    user=request.user
    sellpairs_list=SellPair.objects.all().order_by('product')
    return render(request, 'locations/locationslist.html', {'locations':locations,'user':request.user, 'sellpairs':sellpairs_list})

abastos/templates/locations/location_details.html
{% extends 'base_layout.html'%}

{% block content %}
{% load static from staticfiles %}
      <button id="details" style="float:left; margin-left: 10%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 20px;background-color: green; color:white;">
      <a style="text-decoration:none; color:white;" href="/locations/locations-list"><i class="fas fa-arrow-circle-left"></i> Back to locations' list</a></button><br />


      <h1>Details of the location</h1>
      <div style="  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color: white; margin-left:20%; font-size: 23px; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px;">
        <b style="color: #ff5f3b;" >Name:</b> {{location.name}} <br />
        <b style="color: #ff5f3b;">North coordinate:</b> {{location.north_coordinate}} <br />
        <b style="color: #ff5f3b;">East coordinate:</b> {{location.east_coordinate}} <br />
      </div>
      {% if user == location.owner %}
      <h2 style="margin-bottom:2%;"> Do you want to make changes ? </h2>
      {% if isName == False %}
      <h5 style="color:red;">The name format isn't correct</h5>
      {% endif %}
      {% if isLat == False %}
      <h5 style="color:red;">The north coordinate's format isn't correct</h5>
      {% endif %}
      {% if isLong == False %}
      <h5 style="color:red;">The east coordinate's format isn't correct</h5>
      {% endif %}
      <form action="{% url 'locations:location_details' slug=location.slug %}" method="post" enctype="multipart/form-data">
        <input type="hidden" name="length" value=8>
        {% csrf_token %}
        <label><b>Name</b></label>
        <input type="text" name="name"  value="{{location.name}}">
        <label><b>North coordinate</b></label>
        <input type="number" step="0.01" name="north_coordinate"  value="{{location.north_coordinate}}">
        <label><b>East coordinate</b></label>
        <input type="number"  step="0.01" name="east_coordinate"  value="{{location.east_coordinate}}"><br />
        <input type="submit"  style="font-size: 25px; margin-top: 3%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color:orange; color:white;" value="Modify" />
        </form>

        {% endif %}




      </div>
{% endblock %}

abastos/templates/locations/locationslist.html
{% extends 'base_layout.html'%}

{% block content %}
{% load static from staticfiles %}
      <h1>Locations where to find your favorite products</h1>

      <button style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color:#ff5f3b; border:0; font-family:'Montserrat', sans-serif; font-size: 25px;"><a  style="color:white; text-decoration:inherit;" href="/locations/publish" >
      Add new place </a></button>

      {% if user.is_authenticated %}
      <div class="myLocations">
        <h1 style="font-size: 40px;">My places</h1>
        {% for location in locations %}
        {% if location.owner == user %}
          <div class="location">
              <div class="container" style="margin-top:30px;">

                <h2 style="padding-top:2%;">
                    <img style="height:30px;" src="https://img.icons8.com/wired/64/000000/building.png"/>
                  {{location.name}}
                </h2>

                <div  id='{{location.id}}' style="background-color: #f0f0f0; display:none; margin-left:20%; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px;">
                  <ul style="list-style-type:none;">
                    {% for sellpair in sellpairs %}
                    {% if sellpair.sell.location == location %}

                      <li style="background-color:white; margin-right:5%; padding-top:2%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); margin-bottom:2%;">
                        <img style="height:15px;" src="{{sellpair.product.url}}"/> <b>{{sellpair.quantity}}</b> units of <b>{{sellpair.product}}</b><br />
                        <em><b>{{sellpair.sell.author}}</b> in <b>{{sellpair.sell.location}}</b></em><br />
                        <a style=" color: #616161; " href="{% url 'sell:sell_details' slug=sellpair.slug  %}"> See details</a>
                      </li>

                    {% endif %}
                    {% endfor %}
                  </ul>
                </div>


                <button onclick="myFunction({{location.id}})" id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: green; color:white;margin-top: 3%; margin-bottom: 2%;"> View ads</button>
                <button id="details" style=" box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: orange; color:white;margin-top: 3%; margin-bottom: 2%;"> <a style="text-decoration:none; color:white;" href="{% url 'locations:location_details' slug=location.slug %}">Modify</a></button>
              <button id="details" style=" box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: red; color:white;margin-top: 3%; margin-bottom: 2%;"> <a style="text-decoration:none; color:white;" href="{% url 'locations:location_delete' slug=location.slug %}">Delete</a></button>




              </div>
          </div>
          {% endif %}

        {% endfor %}

      </div>

      <div class="otherLocations">
        <h1 style="font-size: 40px;"> Other places</h1>
        {% for location in locations %}
        {% if location.owner != user %}
          <div class="location">
              <div class="container" style="margin-top:30px;">

                <h2 style="padding-top:2%;">
                    <img style="height:30px;" src="https://img.icons8.com/wired/64/000000/building.png"/>
                  {{location.name}}
                </h2>
                <h4><b>Owner:</b> {{location.owner}}</h4>

                <div  id='{{location.id}}' style="background-color: #f0f0f0; display:none; margin-left:20%; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px;">
                  <ul style="list-style-type:none;">
                    {% for sellpair in sellpairs %}
                    {% if sellpair.sell.location == location %}

                    <li style="background-color:white; margin-right:5%; padding-top:2%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); margin-bottom:2%;">
                      <img style="height:15px;" src="{{sellpair.product.url}}"/> <b>{{sellpair.quantity}}</b> units of <b>{{sellpair.product}}</b><br />
                      <em><b>{{sellpair.sell.author}}</b> in <b>{{sellpair.sell.location}}</b></em><br />
                      <a style=" color: #616161; " href="{% url 'sell:sell_details' slug=sellpair.slug  %}"> See details</a>
                    </li>

                    {% endif %}
                    {% endfor %}
                  </ul>
                </div>


                <button onclick="myFunction({{location.id}})" id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: green; color:white;margin-top: 3%; margin-bottom: 2%;"> View ads</button>


              </div>
          </div>
          {% endif %}

        {% endfor %}

      </div>

      {% else %}
      <div class="otherLocations">
        <h1 style="font-size: 40px;">Places</h1>
        {% for location in locations %}
        {% if location.owner != user %}
          <div class="location">
              <div class="container" style="margin-top:30px;">

                <h2 style="padding-top:2%;">
                    <img style="height:30px;" src="https://img.icons8.com/wired/64/000000/building.png"/>
                  {{location.name}}
                </h2>
                <h4><b>Owner:</b> {{location.owner}}</h4>

                <div  id='{{location.id}}' style="background-color: #f0f0f0; display:none; margin-left:20%; margin-right:20%; padding-top:10px; padding-bottom:10px; border:2px;">
                  <ul style="list-style-type:none;">
                    {% for sellpair in sellpairs %}
                    {% if sellpair.sell.location == location %}

                    <li style="background-color:white; margin-right:5%; padding-top:2%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); margin-bottom:2%;">
                      <img style="height:15px;" src="{{sellpair.product.url}}"/> <b>{{sellpair.quantity}}</b> units of <b>{{sellpair.product}}</b><br />
                      <em><b>{{sellpair.sell.author}}</b> in <b>{{sellpair.sell.location}}</b></em><br />
                      <a style=" color: #616161; " href="{% url 'sell:sell_details' slug=sellpair.slug  %}"> See details</a>
                    </li>

                    {% endif %}
                    {% endfor %}
                  </ul>
                </div>


                <button onclick="myFunction({{location.id}})" id="details" style="box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 17px;background-color: green; color:white;margin-top: 3%; margin-bottom: 2%;"> View ads</button>


              </div>
          </div>
          {% endif %}

        {% endfor %}

      </div>

      {% endif %}



      <script>
      function myFunction(value) {
        var x = document.getElementById(value);
        if (x.style.display === "none") {
          x.style.display = "block";
        } else {
          x.style.display = "none";
        }
      }


      </script>

{% endblock %}

abastos/templates/locations/publish.html
{% extends 'base_layout.html'%}

{% block content %}
{% load static from staticfiles %}
   <button id="details" style="float:left; margin-left: 10%; box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); font-family: 'Montserrat', sans-serif;font-size: 20px;background-color: green; color:white;">
    <a style="text-decoration:none; color:white;" href="/locations/locations-list"><i class="fas fa-arrow-circle-left"></i> Back to locations' list</a></button> <br />

      <h1>Add a new place here:</h1>



      <h2 style="margin-bottom: 3%;"> What location do you want to add? </h2>
      {% if isName == False %}
      <h5 style="color:red;">The name format isn't correct</h5>
      {% endif %}
      {% if isLat == False %}
      <h5 style="color:red;">The north coordinate's format isn't correct</h5>
      {% endif %}
      {% if isLong == False %}
      <h5 style="color:red;">The east coordinate's format isn't correct</h5>
      {% endif %}
      <form action="/locations/publish/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <br />
        <input type="submit" style="font-size: 25px;  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); background-color: lightblue; color:white; margin-top:3%;" value="Add new place" />
      </form>





      </div>
{% endblock %}